In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)

A

array([-4.21625337e-01,  2.99138322e+00, -2.16237959e+00, -1.74737353e+00,
        1.22378724e+00, -3.62329253e-01,  3.76019822e-02,  8.70727748e-01,
       -1.11514847e-03,  9.48777672e-01])

In [6]:
B = np.random.randn(10)

B

array([ 1.04815724, -0.14141596, -1.24317429,  1.09171832, -0.08422282,
        0.24935847, -0.36078122,  0.56568746, -0.09396665,  0.42661719])

In [7]:
# Binary Functions
np.add(A,B)

array([ 0.6265319 ,  2.84996725, -3.40555388, -0.65565521,  1.13956442,
       -0.11297078, -0.32317924,  1.43641521, -0.0950818 ,  1.37539486])

In [8]:
np.maximum(A,B)

array([ 1.04815724e+00,  2.99138322e+00, -1.24317429e+00,  1.09171832e+00,
        1.22378724e+00,  2.49358468e-01,  3.76019822e-02,  8.70727748e-01,
       -1.11514847e-03,  9.48777672e-01])

In [9]:
website = 'https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True